name: qiskit-rise-environment
channels:
  - conda-forge
dependencies:
  - python==3.6
  - pip=18
  - numpy
  - pandas
  - bokeh
  - rise
  - qiskit
  - matplotlib
  - notebook
  - ipywidgets
  - pip:
    - qiskit
    - qiskit-aqua
