name: qiskit-rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip==19.0.1
  - numpy
  - rise
  - matplotlib
  - notebook
  - ipywidgets
  - pip:
    - qiskit==0.7.0
    - qiskit_aqua
    - qiskit_util
    - wget
    - tabulate
