name: qiskit-rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - bokeh
  - rise
  - matplotlib
  - notebook
  - ipywidgets
  - pip:
    - qiskit
    - qiskit-aqua
